import type { Metadata } from "next";
import Head from "next/head";
import WaterQualityProvider from "@/app/context/WaterQualityProvider";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <WaterQualityProvider>
            {children}
          </WaterQualityProvider>
        </body>
    </html>
  );
}
